[build]
builder = "nixpacks"
buildCommand = "pip install -r server/requirements.txt"

[deploy]
startCommand = "uvicorn server.app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
